class WordsEn {
  // five letter words
static const List<List<String>> fiveLetters = [
    ["apple", "A round fruit often associated with health and temptation."],
    ["chair", "A piece of furniture designed for sitting."],
    ["house", "A place where people live, often with a roof and walls."],
    ["money", "A medium of exchange used to buy goods and services."],
    [
      "water",
      "A clear liquid essential for life, covering much of the Earth's surface."
    ],
    ["anger", "A strong feeling of displeasure or hostility."],
    ["doubt", "A feeling of uncertainty or lack of conviction."],
    ["peace", "A state of calm or tranquility, often free from conflict."],
    ["pride", "A feeling of satisfaction or self-worth, sometimes excessive."],
    ["truth", "The quality of being in accordance with fact or reality."],
    ["arena", "A large open space for sports or other activities."],
    ["baker", "A person who bakes bread and other baked goods."],
    ["canal", "An artificial waterway for navigation or irrigation."],
    ["ferry", "A boat that carries people, vehicles, or goods across water."],
    ["vivid", "Producing strong, clear, or powerful images or impressions."],
    ["storm", "A disturbance in the atmosphere with wind and precipitation."],
    ["cabin", "A small, simple house, often in the woods or mountains."],
    ["cargo", "Goods carried by a ship, airplane, or vehicle."],
    ["glory", "High renown or honor won by notable achievements."],
    ["lemon", "A yellow citrus fruit with a sour taste."],
    ["manor", "A large house with land; a noble's estate."],
    ["ocean", "A vast body of salt water covering much of Earth's surface."],
    [
      "patch",
      "A small area of ground or cloth different from its surroundings."
    ],
    ["realm", "A kingdom or domain; an area of activity or interest."],
    [
      "siren",
      "A device that makes a loud warning sound, or a mythical creature."
    ],
    ["wrath", "Intense anger, often associated with a desire for revenge."],
    ["moose", "A large, long-legged mammal found in northern forests."],
    ["quail", "A small ground-dwelling bird."],
    ["aroma", "A pleasant or distinctive smell."],
    ["stone", "A hard, solid mineral material of rock."],
    ["chalk", "A soft white limestone, often used for writing on blackboards."],
    ["flame", "The visible, hot gaseous part of a fire."],
    ["honey", "A sweet, sticky substance made by bees."],
    ["ivory", "A hard, white material from the tusks of elephants."],
    ["jetty", "A structure extending into water to protect a shore."],
    ["koala", "An Australian marsupial with a distinctive face."],
    ["llama", "A South American animal valued for its wool."],
    ["maple", "A type of tree known for its distinctive leaves and sap."],
    ["nanny", "A person, usually a woman, who cares for children."],
    [
      "olive",
      "A small, oval fruit with a bitter flavor, often used in cooking."
    ],
    ["pivot", "A central point, pin, or shaft on which a mechanism turns."],
    [
      "query",
      "A question, often one expressing doubt or requesting information."
    ],
    ["ridge", "A long, narrow hilltop or mountain range."],
    ["sheep", "A domesticated animal raised for wool, milk, and meat."],
    ["thumb", "The short, thick first digit of the human hand."],
    ["ultra", "Beyond; on the far side of a threshold or limit."],
    [
      "vault",
      "An arched structure forming a roof or ceiling, or a secure room for valuables."
    ],
    ["whisk", "A utensil for whipping eggs or other ingredients."],
    [
      "yeast",
      "A microorganism used in baking and brewing to ferment dough or liquid."
    ],
    ["zebra", "An African wild horse with black-and-white stripes."],
    ["beech", "A type of tree with smooth gray bark and glossy leaves."],
    [
      "crust",
      "The tough outer part of a loaf of bread or the Earth's outer layer."
    ],
    ["daisy", "A small flower with a yellow center and white petals."],
    ["eagle", "A large bird of prey known for its keen sight."],
    [
      "fauna",
      "The animals characteristic of a region, period, or special environment."
    ],
    ["globe", "A spherical model of the Earth or another celestial body."],
    [
      "hedge",
      "A fence or boundary formed by closely planted shrubs or bushes."
    ],
    ["inbox", "A place where incoming mail or messages are received."],
    ["jewel", "A precious stone, often set in jewelry."],
    [
      "kneel",
      "To rest on one's knees as a gesture of respect, submission, or prayer."
    ],
    ["lunar", "Relating to the moon."],
    ["mango", "A tropical fruit with sweet orange flesh and a large pit."],
    [
      "nylon",
      "A synthetic fabric or material known for strength and elasticity."
    ],
    ["oasis", "A fertile spot in a desert where water is found."],
    ["pivot", "A central point on which something turns or balances."],
    ["quill", "A large feather, especially one used as a pen."],
    ["raven", "A large bird with black feathers and a harsh voice."],
    [
      "spade",
      "A tool with a sharp-edged, typically rectangular, metal blade and a long handle."
    ],
    ["thief", "A person who steals another's property."],
    ["untie", "To undo or loosen a knot or binding."],
    ["vivid", "Strikingly bright or intense."],
    ["whale", "A large marine mammal known for its size and intelligence."],
    ["yacht", "A medium-sized sailboat for cruising or racing."],
    ["zonal", "Relating to or arranged in zones."],
    ["angel", "A spiritual being often depicted as a messenger from heaven."],
    ["brink", "The edge of a steep place or a point of decision."],
    ["cable", "A thick, strong rope or a bundle of wires."],
    ["drain", "A channel or pipe that removes liquid waste."],
    ["frost", "A deposit of small white ice crystals formed on surfaces."],
    ["grill", "A device used to cook food over an open flame."],
    ["hazel", "A type of tree that produces edible nuts."],
    ["irony", "A situation or expression opposite to what is expected."],
    ["jumbo", "An adjective for something very large."],
    ["karma", "A belief that actions in life determine future fate."],
    ["lodge", "A small house, often in the wilderness."],
    ["medal", "An award given as a reward for bravery, achievement, etc."],
    ["nylon", "A synthetic fabric used for making clothes, ropes, etc."],
    ["ocean", "The vast body of salt water covering much of Earth's surface."],
    ["plume", "A large feather or something resembling it, often decorative."],
    ["quest", "A search or pursuit made in order to find something."],
    ["rider", "A person who rides an animal or vehicle."],
    ["scent", "A distinctive smell, often pleasant."],
    ["tiger", "A large carnivorous feline with a striped coat."],
    ["ultra", "Beyond the ordinary or extreme."],
    ["value", "The worth, importance, or usefulness of something."],
    ["whisk", "A utensil for stirring or beating."],
    ["yacht", "A medium-sized sailboat or vessel."],
    ["zebra", "A wild African horse with black-and-white stripes."],
      [
      "gnome",
      "A small mythical being often depicted with a beard and pointed hat."
    ],
    [
      "sojas",
      "A type of bean, commonly used in Asian cuisine and for soy products."
    ],
    ["necks", "The part of the body connecting the head to the torso."],
    ["papal", "Relating to the pope or the papacy."],
    ["conge", "Official leave or dismissal, often used in formal contexts."],
    ["rides", "Wrinkles or creases on the skin, especially due to aging."],
    ["gongs", "A large metal disc that makes a resonant sound when struck."],
    ["minas", "Units of ancient weight or currency."],
    ["abuse", "Improper use or treatment, often with harmful effects."],
    ["mount", "To climb or ascend, or to place something on a support."],
    ["balls", "Spherical objects used in various sports and games."],
    ["colts", "Young male horses."],
    ["cite", "To quote as evidence or refer to as an example."],
    ["rames", "A type of oar used for rowing."],
    ["fugue", "A musical composition with interwoven melodies."],
    ["truth", "Conformity to fact or reality."],
    ["ethos", "The characteristic spirit or culture of a community."],
    ["karma", "The concept that actions in this life affect future fates."],
    ["oasis", "A fertile spot in a desert, often with water."],
    ["umbra", "The darkest part of a shadow."],
    ["xenon", "A colorless gas used in lamps and for research."],
    ["heart", "An organ that pumps blood throughout the body."],
    ["night", "The period of darkness between sunset and sunrise."],
    ["earth", "The planet we live on."],
    ["angel", "A spiritual being often seen as a messenger from God."],
    ["laugh", "To express joy or amusement through sound."],
    ["beach", "A shore area covered with sand or pebbles."],
    ["craft", "Skillful activity or a handmade object."],
    ["train", "A series of connected vehicles traveling on rails."],
    ["block", "A solid, rectangular piece of material."],
    ["clock", "A device for telling time."],
    ["court", "A place where justice is administered or a sports area."],
    ["crown", "A royal headpiece, symbolizing authority."],
    ["grass", "A common green plant in fields and lawns."],
    ["brush", "A tool for painting or cleaning."],
    ["plant", "A living organism that grows in soil and absorbs sunlight."],
    ["store", "A place where goods are sold."],
    ["smile", "A facial expression showing pleasure or friendliness."],
    ["creek", "A small stream or tributary of a river."],
    ["globe", "A spherical model of Earth."],
    ["scale", "A tool for measuring weight or size."],
    ["sheep", "A farm animal known for its wool."],
    ["ghost", "A spirit of a dead person believed to appear to the living."],
    ["flame", "The visible, gaseous part of a fire."],
    ["stone", "A hard, solid mineral substance."],
    ["sword", "A weapon with a long metal blade."],
    ["grape", "A small, round fruit used in making wine."],
    ["melon", "A large, juicy fruit with a thick rind."],
    ["spoon", "A utensil used for eating or serving."],
    ["field", "An open area, often used for farming or sports."],
    ["tower", "A tall, narrow structure, often part of a building."],
    ["ridge", "A long, narrow hilltop or mountain range."],
    ["flour", "A powder made from ground grains used in baking."],
    ["drain", "A pipe or channel for removing liquid."],
    ["giant", "An unusually large person or thing."],
    ["noble", "Belonging to a high social class with honorable qualities."],
    ["blaze", "A large, intense fire."],
    ["frost", "A thin layer of ice crystals on surfaces in cold weather."],
    ["steel", "A strong metal alloy used in construction and manufacturing."],
    ["liver", "An organ in the body that processes toxins."],
    ["petal", "A colorful part of a flower."],
    ["whale", "A large marine mammal."],
    ["brace", "A device used to support or stabilize parts of the body."],
    ["flock", "A group of birds or animals."],
    ["pouch", "A small bag used for carrying things."],
    ["shelf", "A flat board used to hold items, often on a wall."],
    ["tiger", "A large wild cat known for its striped coat."],
    ["paint", "A colored substance applied to surfaces for decoration."],
    ["vapor", "A gaseous state of a substance."],
    ["flute", "A musical instrument played by blowing air across a hole."],
    ["quest", "A journey made in search of something."],
    ["pearl", "A smooth, round object formed inside oysters."],
    ["spice", "A substance used to flavor food, like cinnamon or pepper."],
    ["weave", "To interlace threads to form a fabric."],
    ["brass", "A yellow metal alloy used in instruments and decorations."],
    ["badge", "A small emblem worn as a symbol of achievement or status."],
    ["trout", "A freshwater fish found in rivers and streams."],
    ["cliff", "A steep rock face, usually beside a sea or lake."],
    ["lemon", "A sour, yellow citrus fruit."],
    ["fence", "A barrier enclosing or bordering an area."],
    ["valor", "Great courage in facing danger."],
    ["crisp", "Firm and fresh, often describing food textures."],
    ["quilt", "A warm bed covering made of layers of fabric."],
    ["kneel", "To go down on one's knees."],
    ["gleam", "A faint, bright shine or glimmer."],
    ["bloom", "A flower, especially when it's at its prime."],
    ["olive", "A small fruit used to make olive oil."],
    ["scout", "A person sent to gather information."],
    ["brook", "A small stream or creek."],
    ["plume", "A feather or something that resembles a feather."],
    ["scrub", "To clean something by rubbing it vigorously."],
    ["flint", "A hard stone used historically to make sparks."],
    ["brick", "A rectangular block used for building walls."],
    ["chess", "A board game for two players using strategic moves."],
    ["grill", "A cooking device with a grated surface over heat."],
    ["torch", "A handheld source of light, typically with a flame."],
    ["crane", "A bird with long legs or a machine for lifting heavy items."],
    ["peach", "A juicy fruit with fuzzy skin."],
    ["skirt", "A garment worn from the waist down, typically by women."],
    ["thyme", "An herb used in cooking."],
    ["chalk", "A soft, white limestone used for writing on blackboards."],
    ["troop", "A group of soldiers or scouts."],
    ["swing", "A seat that moves back and forth, typically in playgrounds."],
    ["amber", "A yellowish fossil resin used in jewelry."],
    ["thorn", "A sharp point on the stem of some plants."],
    ["swoop", "To descend suddenly in a sweeping motion."],
    ["blend", "To mix together thoroughly."],
    ["trace", "A small amount or sign of something."],
    ["stoic", "A person who endures pain without showing it."],
    ["yeast", "A microorganism used in baking and brewing."],
    ["align", "To arrange in a straight line."],
    // Additional entries as needed...
  ];

  // six letter words
  static const List<String> sixLetters = [
    "unsays",
    "clonal",
    "brills",
    "befoul",
    "beaded",
    "larval",
    "cassia",
    "emcees",
    "schist",
    "makuta",
    "livens",
    "jejune",
    "peepul",
    "jingle",
    "whites",
    "yautia",
    "scries",
    "licked",
    "teraph",
    "cranny",
    "storks",
    "diking",
    "shawms",
    "precut",
    "blonde",
    "screes",
    "stelar",
    "fusuma",
    "within",
    "muskie",
    "sordid",
    "osiers",
    "reseen",
    "sauger",
    "looted",
    "stamen",
    "delude",
    "snorer",
    "finery",
    "dashed",
    "banged",
    "depict",
    "hedged",
    "aurous",
    "legers",
    "geared",
    "bookoo",
    "clacks",
    "purest",
    "ponged",
    "dingus",
    "direst",
    "wammus",
    "lifted",
    "harper",
    "stilts",
    "craped",
    "fiddle",
    "tackle",
    "drongo",
    "dabbed",
    "bonsai",
    "shavie",
    "uremic",
    "custom",
    "photos",
    "gabber",
    "strobe",
    "trolly",
    "cannon",
    "witing",
    "oscine",
    "tauons",
    "harped",
    "damask",
    "saluki",
    "confit",
    "chally",
    "lurers",
    "fermis",
    "posing",
    "coward",
    "rectum",
    "draped",
    "devote",
    "shroff",
    "sweaty",
    "leaver",
    "costal",
    "roomer",
    "drying",
    "exodoi",
    "trench",
    "abuser",
    "vocals",
    "zonked",
    "aldrin",
    "coacts",
    "kolhoz",
    "sampan"
  ];


  // seven letter words
  static const List<String> sevenLetters = [
    "preload",
    "drownds",
    "beaches",
    "helotry",
    "inhuman",
    "frazzle",
    "biggins",
    "spinout",
    "boggier",
    "florist",
    "shairns",
    "jokiest",
    "whitter",
    "fellest",
    "doodads",
    "nurture",
    "palping",
    "ozonate",
    "aseptic",
    "resects",
    "ragtags",
    "misplan",
    "outmode",
    "rebloom",
    "outpray",
    "dangers",
    "bedtick",
    "aroynts",
    "glycyls",
    "sallied",
    "giddily",
    "entrant",
    "uploads",
    "balkier",
    "subadar",
    "shirked",
    "seriate",
    "garbled",
    "ruckles",
    "wealths",
    "tackily",
    "doggrel",
    "velaria",
    "densely",
    "laments",
    "misdone",
    "assured",
    "rotches",
    "pavanes",
    "prosers",
    "misease",
    "apraxic",
    "huffing",
    "noising",
    "mashing",
    "ripieno",
    "panders",
    "octuple",
    "oxidant",
    "amboina",
    "grasper",
    "bridged",
    "fatling",
    "monadic",
    "gawkish",
    "chylous",
    "bigfeet",
    "pensils",
    "girthed",
    "spicier",
    "kvelled",
    "gustier",
    "notions",
    "chomper",
    "luggage",
    "gomerel",
    "saddens",
    "broking",
    "undraws",
    "reeling",
    "ungated",
    "fandoms",
    "fingers",
    "misgave",
    "cultish",
    "arguing",
    "feelers",
    "spelled",
    "settees",
    "limbier",
    "murkier",
    "hocking",
    "plumber",
    "plenary",
    "sabbath",
    "despair",
    "possums",
    "lithest",
    "foining",
    "reddish"
  ];
}